### ISSUE TITLE
有没有办法只给中文包裹上$t 不替换成key 就把中文做为key 对应的值也是中文,这样就不会有重复的而且很方便动态编辑

### ISSUE THREAD

**Issue by jipika** [RichieChoo/vue-swift-i18n#10]

**Comment by hujinbin** [comment]
> _No description provided._

可以试试这个我这个，很方便
https://github.com/hujinbin/webpack-i18n-loader

**Comment by jipika** [comment]
非常感觉我很需要这个东西😊

**Comment by RichieChoo** [comment]
保留重复的原因是需要后期维护，所有有了scope的概念，开始就是设计的不重复，结果很不符合预期，尤其是这个重复的key对应调整了之后，影响面太广了
