### ISSUE TITLE
有些情况的中文匹配不出来

### ISSUE THREAD

**Issue by yubaoquan** [RichieChoo/vue-swift-i18n#2]
```
<div>
    我我我
    你你你
    他他他
</div>
<div>你好<span>张三</span>先生</div>
```
上面这种情况, 标签内有多行中文, 和中文内有标签的情况, 都抽取不出来

**Comment by RichieChoo** [comment]
v0.3.0 [已经修复。有些特殊的情况无法使用正则匹配出，详情见](https://github.com/RichieChoo/vue-swift-i18n/blob/master/retrieveAndReplace.md)


感谢使用

**Comment by yubaoquan** [comment]
建议使用kiwi-linter的做法, 用ast做匹配
