### ISSUE TITLE
可以增加一个设置选项把所有的字段放在同一层级吗？这样可以避免同样的文字在不同页面被多次提取。

### ISSUE THREAD

**Issue by Leslie-Luo** [RichieChoo/vue-swift-i18n#5]
![image](https://user-images.githubusercontent.com/22937782/109095609-0eda9c00-7757-11eb-8316-37f8d9f5b26b.png)
图中的**切换语言**在两个页面都存在，被插件提取了两次。能不能增加一个配置把提取的结果放在同一层级，这样在其他页面提取文字时就可以避免同样的文字被提取多次。效果如下图所示↓
![image](https://user-images.githubusercontent.com/22937782/109095846-75f85080-7757-11eb-94fb-f3e8e166cb56.png)

**Comment by liub-work** [comment]
之前项目遇到同样问题, 改造了一下插件解决了这个问题, 只是我没有权限提交
解决思路就是增加一个是否使用文件名做key的设置项, key拼接逻辑进行更改, 并且修正了一下level = 0时候默认拼接全路径问题

[patch.txt](https://github.com/RichieChoo/vue-swift-i18n/files/6315197/patch.txt)

patch里有点乱, 因为跟作者的格式不一样, 主要修改文件只有三个
![选区_106](https://user-images.githubusercontent.com/71386374/114816304-72458980-9dea-11eb-9289-47a8967b76ac.png)

插件还是用的很舒服, 虽然还有一些替换问题, 但是已经解决了不少问题

**Comment by RichieChoo** [comment]
当时设计scope的初衷：
1. 同一个汉语单词对应的key是相通的，当这个key的值改变，多个引用的地方未知，在这个key要做调整时，会产生很广泛的未知影响，尤其在类似lerna管理的多模块应用中。
2. 在进行扫描一个文件的汉语时，在还没有进行替换时，有可能会生成无用key,val，用scope概念是每次的更新替换等只在scope里操作，保证scope干净正确的同时，不对其他文件的国际化配置产生影响

> 如果真有对应的需求，可以提个PR，把功能抽成配置@liub-work

**Comment by liub-work** [comment]
@RichieChoo PR已经提交, 设计初衷没有改变, 发现问题是目录如果0或者负数时默认key拼接是全路径, patch改善了这个问题, 并且添加个设置支持不使用文件名作为key, 这样自然而然支持了本身这个issue, 当初项目使用原设计方式做的, 重复性太高, 考虑后期维护, 整合了这个patch, 1500多个国际化重构就剩500个, PM痛苦翻译

**Comment by RichieChoo** [comment]
已经并入主分支，发布0.4.2版本
