### ISSUE TITLE
部分中文状态无法识别

### ISSUE THREAD

**Issue by liub-work** [RichieChoo/vue-swift-i18n#6]
最近使用时候发现中文中包含':'或'·'无法正常截取中文内容
`<span>姓名:</span>`
`<span label="姓名:"></span`
`<span label="·概况"></span`

**Comment by RichieChoo** [comment]
1. 因为是用正则前后断言等进行匹配的，能扫描的汉字要符合[约定](https://github.com/RichieChoo/vue-swift-i18n/blob/master/README_DETAIL.md#%E6%8F%92%E4%BB%B6%E8%AF%A6%E8%BF%B0)
2. 这些特殊字符当初我还是特意加上的😅，为了过滤用户在错误的语法中扫描出来的一些汉字


后续会加入 在扫描前将所有的扫描的汉字list展示在webview中，包括含有特殊字符的字符串，给用户可以动态选择的能力
